import { connect } from "react-redux";
import {
  handleFetchBooks,
  handleFetchPlugins,
  handleFetchBookSortCode,
  handleFetchNoteSortCode,
  handleFetchViewMode,
  handleDetailDialog,
  handleLoadingDialog,
  handleNewDialog,
  handleShowSupport,
  handleSetting,
  handleLocalFileDialog,
  handleImportDialog,
  handleOPDSDialog,
  handleJmcomicDialog,
  handlePicaDialog,
  handleAutoImportDialog,
  handleFetchNotes,
  handleFetchBookmarks,
  handleEditDialog,
  handleDeleteDialog,
  handleAddDialog,
  handleTranslateDialog,
  handleReadingState,
  handleShowPopupNote,
  handleSortShelfDialog,
  handleExportShareDialog,
  handleImportShareDialog,
  handleShelf,
  handleMode,
  handleFilterDisplay,
} from "../../store/actions";
import { withTranslation } from "react-i18next";

import "./manager.css";
import { stateType } from "../../store";
import Manager from "./component";
import { withRouter } from "react-router-dom";
const mapStateToProps = (state: stateType) => {
  return {
    books: state.manager.books,
    mode: state.sidebar.mode,
    cloudSyncFunc: state.book.cloudSyncFunc,
    importBookFunc: state.book.importBookFunc,
    shelfTitle: state.sidebar.shelfTitle,
    isOpenEditDialog: state.book.isOpenEditDialog,
    isDetailDialog: state.manager.isDetailDialog,
    isAuthed: state.manager.isAuthed,
    isOpenDeleteDialog: state.book.isOpenDeleteDialog,
    isOpenAddDialog: state.book.isOpenAddDialog,
    isSettingOpen: state.manager.isSettingOpen,
    isAboutOpen: state.manager.isAboutOpen,
    isSortDisplay: state.manager.isSortDisplay,
    isFilterDisplay: state.manager.isFilterDisplay,
    isShowLoading: state.manager.isShowLoading,
    isShowNew: state.manager.isShowNew,
    isShowSupport: state.manager.isShowSupport,
    isShowPopupNote: state.manager.isShowPopupNote,
    isOpenImportDialog: state.backupPage.isOpenImportDialog,
    isOpenOPDSDialog: state.backupPage.isOpenOPDSDialog,
    isOpenJmcomicDialog: state.backupPage.isOpenJmcomicDialog,
    isOpenPicaDialog: state.backupPage.isOpenPicaDialog,
    isOpenAutoImportDialog: state.backupPage.isOpenAutoImportDialog,
    isOpenSortShelfDialog: state.backupPage.isOpenSortShelfDialog,
    isOpenLocalFileDialog: state.backupPage.isOpenLocalFileDialog,
    isOpenExportShareDialog: state.backupPage.isOpenExportShareDialog,
    isOpenImportShareDialog: state.backupPage.isOpenImportShareDialog,
    isOpenTranslateDialog: state.book.isOpenTranslateDialog,
    currentBook: state.book.currentBook,
  };
};
const actionCreator = {
  handleFetchBooks,
  handleFetchPlugins,
  handleFetchNotes,
  handleSetting,
  handleFetchBookmarks,
  handleFetchBookSortCode,
  handleFetchNoteSortCode,
  handleFetchViewMode,
  handleEditDialog,
  handleDeleteDialog,
  handleAddDialog,
  handleTranslateDialog,
  handleDetailDialog,
  handleSortShelfDialog,
  handleLoadingDialog,
  handleNewDialog,
  handleShowSupport,
  handleLocalFileDialog,
  handleImportDialog,
  handleOPDSDialog,
  handleJmcomicDialog,
  handlePicaDialog,
  handleAutoImportDialog,
  handleExportShareDialog,
  handleImportShareDialog,
  handleReadingState,
  handleShowPopupNote,
  handleShelf,
  handleMode,
  handleFilterDisplay,
};
export default connect(
  mapStateToProps,
  actionCreator
)(withTranslation()(withRouter(Manager as any) as any) as any);
